from training_images import extract_inlet_location, panorama_location, closest_panoramas_id, get_multiview
from src.detection_model_training import data_split
from src.segmentation_visualization import process_image_data